"""Comparison utilities for BrainWear 2D: Baseline vs Slot+AA-CBR.

Analogous to compare_pipelines.py but for BrainWear, where the comparison
is shown across k ∈ {2,3,4,5} for each outcome score (QL2, PF2, CF, EF).

Data sources:
  Baseline    -- baseline/brainwear_baseline_cv.json  (generated by brainwear_2d_baseline_cv.py)
  Slot+AA-CBR -- aacbr/leaderboard_trained.json        (eval_trained_brainwear_2d entries)

Outputs (under comparison/):
  figures/compare_brainwear_png.png
  tables/compare_brainwear_png.tex
  tables/compare_brainwear_png.csv
  results/compare_brainwear_png.json
"""

from __future__ import annotations

import csv as csv_mod
import json
import sys
from pathlib import Path

FYP_ROOT = Path(__file__).resolve().parents[1]
if str(FYP_ROOT) not in sys.path:
    sys.path.insert(0, str(FYP_ROOT))

# Reuse style constants from the BraTS comparison module.
from comparison.compare_pipelines import STYLE, chance_level, _fmt, _build_styles  # noqa: F401

# Outcome scores evaluated by both pipelines.
SCORES = ["QL2", "PF2", "CF", "EF"]
NUM_CLASSES = [2, 3, 4, 5]
METHODS_BW = ["Baseline", "Slot+AA-CBR"]

STYLE_BW = {
    "Baseline":    STYLE["Baseline"],
    "Slot+AA-CBR": STYLE["Slot+AA-CBR"],
}

TRAINED_EVAL_SCRIPT = "eval_trained_brainwear_2d"
BASELINE_EVAL_SCRIPT = "baseline_2d_cv"


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

def _load_json(path):
    p = Path(path)
    return json.loads(p.read_text()) if p.exists() else None


def load_baseline_cv(
    lb_path,
    scores: list[str] | None = None,
) -> dict[str, dict[int, dict]]:
    """Load brainwear_baseline_cv.json.

    Returns {score_name: {n_bins: {f1, std, config}}}
    Best-CV-F1 config per (score_name, n_bins) across all pipelines.
    """
    d = _load_json(lb_path)
    if d is None:
        return {}
    rows = [x for x in d
            if x.get("eval_script") == BASELINE_EVAL_SCRIPT
            and x.get("metrics", {}).get("cv_mean_f1") is not None]
    if scores:
        rows = [x for x in rows if x["config"].get("score_name") in scores]

    out: dict[str, dict[int, dict]] = {}
    for x in rows:
        s  = x["config"]["score_name"]
        k  = x["config"]["n_bins"]
        f1 = x["metrics"]["cv_mean_f1"]
        if s not in out:
            out[s] = {}
        if k not in out[s] or f1 > out[s][k]["f1"]:
            out[s][k] = {
                "f1":    float(f1),
                "std":   float(x["metrics"].get("cv_std_f1") or 0.0),
                "config": f"{x['config']['pipeline']} ({x['config']['model']})",
            }
    return out


def load_trained(
    lb_path,
    eval_script: str = TRAINED_EVAL_SCRIPT,
    scores: list[str] | None = None,
    checkpoint: str | None = None,
) -> dict[str, dict[int, dict]]:
    """Load leaderboard_trained.json entries for BrainWear 2D.

    Returns {score_name: {n_bins: {f1, std, config}}}
    Best-CV-F1 AA-CBR config per (score_name, n_bins).
    """
    d = _load_json(lb_path)
    if d is None:
        return {}
    rows = [x for x in d
            if x.get("eval_script") == eval_script
            and x.get("metrics", {}).get("cv_mean_f1") is not None]
    if scores:
        rows = [x for x in rows if x["config"].get("score_name") in scores]
    if checkpoint is not None:
        rows = [x for x in rows if x.get("config", {}).get("checkpoint") == checkpoint]

    out: dict[str, dict[int, dict]] = {}
    for x in rows:
        c  = x["config"]
        s  = c.get("score_name")
        k  = c.get("n_bins")
        f1 = x["metrics"]["cv_mean_f1"]
        if s is None or k is None:
            continue
        if s not in out:
            out[s] = {}
        if k not in out[s] or f1 > out[s][k]["f1"]:
            out[s][k] = {
                "f1":    float(f1),
                "std":   float(x["metrics"].get("cv_std_f1") or 0.0),
                "config": f"{c.get('char_model')}/{c.get('agg_mode')}/{c.get('strategy')}",
            }
    return out


def assemble(
    baseline_lb,
    trained_lb,
    trained_eval_script: str = TRAINED_EVAL_SCRIPT,
    scores: list[str] | None = None,
    checkpoint_labels: dict[str, str] | None = None,
    only_checkpoints: list[str] | None = None,
) -> dict[str, dict]:
    """Load both leaderboards and return a unified data dict.

    Auto-detects unique checkpoints in trained_lb; if more than one is present
    each gets its own key "Slot+AA-CBR (label)".

    Args:
        checkpoint_labels: optional dict mapping checkpoint folder name (e.g.
            ``"brats_png_v14a_gamma4"``) to a custom display label used inside
            the brackets.  Falls back to the folder name when not listed.
        only_checkpoints: optional list of checkpoint folder names to include
            (e.g. ``["brats_png_v14a_gamma4", "brats_png_v20a_attn_skip"]``).
            When ``None`` all checkpoints found in the leaderboard are used.

    Returns:
        {
          "Baseline":             {score: {k: {f1, std, config}}},
          "Slot+AA-CBR (...)":    {score: {k: {f1, std, config}}},  # one per checkpoint
        }
    """
    use_scores = scores or SCORES
    labels = checkpoint_labels or {}

    raw = _load_json(trained_lb) or []
    ckpts = sorted({
        x["config"]["checkpoint"]
        for x in raw
        if x.get("eval_script") == trained_eval_script
        and x.get("config", {}).get("checkpoint")
    })
    if only_checkpoints is not None:
        ckpts = [c for c in ckpts if Path(c).parent.name in only_checkpoints]

    result: dict[str, dict] = {"Baseline": load_baseline_cv(baseline_lb, scores=use_scores)}
    if len(ckpts) <= 1:
        result["Slot+AA-CBR"] = load_trained(
            trained_lb, eval_script=trained_eval_script, scores=use_scores,
            checkpoint=ckpts[0] if ckpts else None)
    else:
        for ckpt in ckpts:
            short = Path(ckpt).parent.name
            display = labels.get(short, short)
            result[f"Slot+AA-CBR ({display})"] = load_trained(
                trained_lb, eval_script=trained_eval_script,
                scores=use_scores, checkpoint=ckpt)
    return result


# ---------------------------------------------------------------------------
# Score ranking
# ---------------------------------------------------------------------------

def rank_scores(
    data: dict[str, dict],
    method: str = "Slot+AA-CBR",
    k: int = 3,
    scores: list[str] | None = None,
) -> list[str]:
    """Rank outcome scores by skill (F1 − 1/k) for *method* at class granularity *k*.

    Scores not present for *method* at *k* are ranked last.
    """
    use_scores = scores or SCORES
    d = data.get(method, {})

    def skill(s):
        entry = d.get(s, {}).get(k)
        if entry is None:
            return -999.0
        return entry["f1"] - chance_level(k)

    return sorted(use_scores, key=skill, reverse=True)


# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------

def make_figure(data: dict, scores: list[str], title: str, out_stub):
    """2×2 grid of subplots (one per outcome score); x=k, lines=methods, dashed chance."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    nrows, ncols = 2, 2
    fig, axes = plt.subplots(nrows, ncols, figsize=(8.4, 7.2), sharey=False)
    axes_flat = axes.flatten()

    methods = list(data.keys())
    styles = _build_styles(methods)

    for idx, score in enumerate(scores[:4]):
        ax = axes_flat[idx]
        for name in methods:
            d = data.get(name, {}).get(score, {})
            ks = [k for k in NUM_CLASSES if k in d]
            if not ks:
                continue
            ys  = [d[k]["f1"]  for k in ks]
            ers = [d[k]["std"]  for k in ks]
            ax.errorbar(ks, ys, yerr=ers, lw=1.8, markersize=6, capsize=3,
                        label=name, zorder=3, **styles[name])
        ax.set_title(score, fontsize=11)
        ax.set_xticks(NUM_CLASSES)
        ax.grid(True, ls=":", alpha=0.5)
        # x-label only on bottom row
        if idx >= ncols:
            ax.set_xlabel("Number of classes $k$")
        # y-label only on left column
        if idx % ncols == 0:
            ax.set_ylabel("Macro-F1 (cross-validation)")
        # legend in top-left panel only
        if idx == 0:
            ax.legend(fontsize=8, framealpha=0.9)

    # Hide any unused axes (if fewer than 4 scores passed)
    for idx in range(len(scores), nrows * ncols):
        axes_flat[idx].set_visible(False)

    fig.suptitle(title, fontsize=12, y=1.01)
    fig.tight_layout()
    fig.savefig(f"{out_stub}.png", bbox_inches="tight", dpi=200)
    plt.close(fig)
    print(f"figure → {out_stub}.png")


# ---------------------------------------------------------------------------
# DataFrame view
# ---------------------------------------------------------------------------

def to_dataframe(data: dict, scores: list[str] | None = None):
    """MultiIndex DataFrame: (method, score) rows × k columns."""
    import pandas as pd
    use_scores = scores or SCORES
    cols = [f"k={k}" for k in NUM_CLASSES]
    idx, rows = [], []
    for name in data:
        for s in use_scores:
            d = data.get(name, {}).get(s, {})
            idx.append((name, s))
            rows.append([d.get(k, {}).get("f1", float("nan")) for k in NUM_CLASSES])
    for s in use_scores:
        idx.append(("Chance (1/k)", s))
        rows.append([chance_level(k) for k in NUM_CLASSES])
    return pd.DataFrame(rows, index=pd.MultiIndex.from_tuples(idx, names=["Method", "Score"]),
                        columns=cols)


def config_dataframe(data: dict, scores: list[str] | None = None):
    """Best AA-CBR config string per (score, k)."""
    import pandas as pd
    use_scores = scores or SCORES
    cols = [f"k={k}" for k in NUM_CLASSES]
    idx, rows = [], []
    for name in data:
        for s in use_scores:
            d = data.get(name, {}).get(s, {})
            idx.append((name, s))
            rows.append([d.get(k, {}).get("config", "--") for k in NUM_CLASSES])
    return pd.DataFrame(rows, index=pd.MultiIndex.from_tuples(idx, names=["Method", "Score"]),
                        columns=cols)


# ---------------------------------------------------------------------------
# CSV export
# ---------------------------------------------------------------------------

def write_csv(data: dict, scores: list[str], out_path) -> None:
    """Long-format CSV: one row per (method, score, k)."""
    with open(out_path, "w", newline="") as f:
        w = csv_mod.writer(f)
        w.writerow(["method", "score", "k", "macro_f1", "std", "config", "chance"])
        for name in data:
            for s in scores:
                for k in NUM_CLASSES:
                    d = data.get(name, {}).get(s, {}).get(k)
                    if not d:
                        continue
                    w.writerow([name, s, k, f"{d['f1']:.4f}",
                                f"{d.get('std', 0.0):.4f}",
                                d.get("config", ""),
                                f"{chance_level(k):.4f}"])
    print(f"csv → {out_path}")


# ---------------------------------------------------------------------------
# LaTeX table
# ---------------------------------------------------------------------------

def make_table(data: dict, scores: list[str], title: str, out_path) -> None:
    """LaTeX table: rows = (method × score), columns = k ∈ {2,3,4,5}."""
    head = " & ".join(f"$k={k}$" for k in NUM_CLASSES)
    lines = [
        "% Auto-generated by comparison/compare_brainwear.py -- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{" + title + ". Macro-F1 (mean $\\pm$ std over 5-fold CV) for "
        "each EORTC outcome score and number of output classes $k$. "
        "\\textbf{Bold} = best per column within each score block. "
        "Chance level is $1/k$.}",
        "\\label{tab:compare-brainwear-png}",
        "\\begin{tabular}{ll" + "c" * len(NUM_CLASSES) + "}",
        "\\toprule",
        "Score & Method & " + head + " \\\\",
        "\\midrule",
    ]

    for si, s in enumerate(scores):
        if si > 0:
            lines.append("\\midrule")
        # Find best per k within this score
        best_per_k: dict[int, str] = {}
        for k in NUM_CLASSES:
            vals = {m: data.get(m, {}).get(s, {}).get(k, {}).get("f1")
                    for m in data}
            vals = {m: v for m, v in vals.items() if v is not None}
            if vals:
                best_per_k[k] = max(vals, key=vals.get)

        for mi, name in enumerate(data):
            cells = []
            for k in NUM_CLASSES:
                d = data.get(name, {}).get(s, {}).get(k)
                txt = _fmt(d)
                if d is not None and best_per_k.get(k) == name:
                    txt = f"\\textbf{{{txt}}}"
                cells.append(txt)
            score_cell = s if mi == 0 else ""
            lines.append(f"{score_cell} & {name} & " + " & ".join(cells) + " \\\\")

        # Chance row per score
        chance_cells = " & ".join(f"{chance_level(k):.3f}" for k in NUM_CLASSES)
        lines.append(f" & \\textit{{Chance}} & {chance_cells} \\\\")

    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"table → {out_path}")

